// <auto-generated />
using System;
using AziendaPaese;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AziendaPaese.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230220135949_CorrectDipendente")]
    partial class CorrectDipendente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AziendaPaese.Entita.Azienda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Attiva")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cap")
                        .HasColumnType("longtext");

                    b.Property<string>("Citta")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataInizioAttivita")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeDirettore")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroTelefono")
                        .HasColumnType("longtext");

                    b.Property<string>("Provincia")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Aziende");
                });

            modelBuilder.Entity("AziendaPaese.Entita.BustaPaga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Banca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DipendenteId")
                        .HasColumnType("int");

                    b.Property<bool>("Pagata")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("StagistaId")
                        .HasColumnType("int");

                    b.Property<int>("SupervisoreRepartoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DipendenteId");

                    b.HasIndex("StagistaId");

                    b.HasIndex("SupervisoreRepartoId");

                    b.ToTable("Bustepaghe");
                });

            modelBuilder.Entity("AziendaPaese.Entita.Dipendente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Attivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CodiceFiscale")
                        .HasColumnType("longtext");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataInizioAttivita")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Iban")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ProgettoId")
                        .HasColumnType("int");

                    b.Property<int>("RepartoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgettoId");

                    b.HasIndex("RepartoId");

                    b.ToTable("Dipendenti");
                });

            modelBuilder.Entity("AziendaPaese.Entita.Progetto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Attivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataInizioAttivita")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Progetti");
                });

            modelBuilder.Entity("AziendaPaese.Entita.Reparto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Attivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("AziendaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataInizioAttivita")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SupervisoreRepartoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AziendaId");

                    b.HasIndex("SupervisoreRepartoId")
                        .IsUnique();

                    b.ToTable("Reparti");
                });

            modelBuilder.Entity("AziendaPaese.Entita.ReporteGiornaliero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DipendenteId")
                        .HasColumnType("int");

                    b.Property<int>("OreLavorate")
                        .HasColumnType("int");

                    b.Property<int>("StagistaId")
                        .HasColumnType("int");

                    b.Property<int>("SupervisoreRepartoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DipendenteId");

                    b.HasIndex("StagistaId");

                    b.HasIndex("SupervisoreRepartoId");

                    b.ToTable("ReportiGiornalieri");
                });

            modelBuilder.Entity("AziendaPaese.Entita.Stagista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Attivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataInizioAttivita")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RepartoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RepartoId");

                    b.ToTable("Stagisti");
                });

            modelBuilder.Entity("AziendaPaese.Entita.SupervisoreReparto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Attivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataInizioAttivita")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RepartoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SupervisoriReparto");
                });

            modelBuilder.Entity("ProgettoStagista", b =>
                {
                    b.Property<int>("ProgettiId")
                        .HasColumnType("int");

                    b.Property<int>("StagistaId")
                        .HasColumnType("int");

                    b.HasKey("ProgettiId", "StagistaId");

                    b.HasIndex("StagistaId");

                    b.ToTable("ProgettoStagista");
                });

            modelBuilder.Entity("AziendaPaese.Entita.BustaPaga", b =>
                {
                    b.HasOne("AziendaPaese.Entita.Dipendente", "Dipendente")
                        .WithMany("BustePaghe")
                        .HasForeignKey("DipendenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AziendaPaese.Entita.Stagista", "Stagista")
                        .WithMany("BustePaghe")
                        .HasForeignKey("StagistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AziendaPaese.Entita.SupervisoreReparto", "SupervisoreReparto")
                        .WithMany("BustePaghe")
                        .HasForeignKey("SupervisoreRepartoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dipendente");

                    b.Navigation("Stagista");

                    b.Navigation("SupervisoreReparto");
                });

            modelBuilder.Entity("AziendaPaese.Entita.Dipendente", b =>
                {
                    b.HasOne("AziendaPaese.Entita.Progetto", null)
                        .WithMany("Dipendenti")
                        .HasForeignKey("ProgettoId");

                    b.HasOne("AziendaPaese.Entita.Reparto", "Reparto")
                        .WithMany("Dipendenti")
                        .HasForeignKey("RepartoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reparto");
                });

            modelBuilder.Entity("AziendaPaese.Entita.Reparto", b =>
                {
                    b.HasOne("AziendaPaese.Entita.Azienda", "Azienda")
                        .WithMany("Reparti")
                        .HasForeignKey("AziendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AziendaPaese.Entita.SupervisoreReparto", "SupervisoreReparto")
                        .WithOne("Reparto")
                        .HasForeignKey("AziendaPaese.Entita.Reparto", "SupervisoreRepartoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Azienda");

                    b.Navigation("SupervisoreReparto");
                });

            modelBuilder.Entity("AziendaPaese.Entita.ReporteGiornaliero", b =>
                {
                    b.HasOne("AziendaPaese.Entita.Dipendente", "Dipenndente")
                        .WithMany("ReportiGiornalieri")
                        .HasForeignKey("DipendenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AziendaPaese.Entita.Stagista", "Stagista")
                        .WithMany("ReportiGiornalieri")
                        .HasForeignKey("StagistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AziendaPaese.Entita.SupervisoreReparto", "SupervisoreReparto")
                        .WithMany("ReportiGiornalieri")
                        .HasForeignKey("SupervisoreRepartoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dipenndente");

                    b.Navigation("Stagista");

                    b.Navigation("SupervisoreReparto");
                });

            modelBuilder.Entity("AziendaPaese.Entita.Stagista", b =>
                {
                    b.HasOne("AziendaPaese.Entita.Reparto", "Reparto")
                        .WithMany("Stagista")
                        .HasForeignKey("RepartoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reparto");
                });

            modelBuilder.Entity("ProgettoStagista", b =>
                {
                    b.HasOne("AziendaPaese.Entita.Progetto", null)
                        .WithMany()
                        .HasForeignKey("ProgettiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AziendaPaese.Entita.Stagista", null)
                        .WithMany()
                        .HasForeignKey("StagistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AziendaPaese.Entita.Azienda", b =>
                {
                    b.Navigation("Reparti");
                });

            modelBuilder.Entity("AziendaPaese.Entita.Dipendente", b =>
                {
                    b.Navigation("BustePaghe");

                    b.Navigation("ReportiGiornalieri");
                });

            modelBuilder.Entity("AziendaPaese.Entita.Progetto", b =>
                {
                    b.Navigation("Dipendenti");
                });

            modelBuilder.Entity("AziendaPaese.Entita.Reparto", b =>
                {
                    b.Navigation("Dipendenti");

                    b.Navigation("Stagista");
                });

            modelBuilder.Entity("AziendaPaese.Entita.Stagista", b =>
                {
                    b.Navigation("BustePaghe");

                    b.Navigation("ReportiGiornalieri");
                });

            modelBuilder.Entity("AziendaPaese.Entita.SupervisoreReparto", b =>
                {
                    b.Navigation("BustePaghe");

                    b.Navigation("Reparto")
                        .IsRequired();

                    b.Navigation("ReportiGiornalieri");
                });
#pragma warning restore 612, 618
        }
    }
}
