// <auto-generated />
using System;
using AziendaPaese;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AziendaPaese.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AziendaPaese.Entita.Azienda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Attiva")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cap")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Citta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataInizioAttivita")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeDirettore")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Aziende");
                });

            modelBuilder.Entity("AziendaPaese.Entita.BustaPaga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Banca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Pagata")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Bustepaghe");
                });

            modelBuilder.Entity("AziendaPaese.Entita.Dipendente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Attivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataInizioAttivita")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Dipendenti");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Dipendente");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AziendaPaese.Entita.Progetto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Attivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataInizioAttivita")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Progetti");
                });

            modelBuilder.Entity("AziendaPaese.Entita.Reparto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Attivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataInizioAttivita")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Reparti");
                });

            modelBuilder.Entity("AziendaPaese.Entita.ReporteGiornaliero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OreLavorate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ReportiGiornalieri");
                });

            modelBuilder.Entity("AziendaPaese.Entita.Stagista", b =>
                {
                    b.HasBaseType("AziendaPaese.Entita.Dipendente");

                    b.HasDiscriminator().HasValue("Stagista");
                });

            modelBuilder.Entity("AziendaPaese.Entita.SupervisoreReparto", b =>
                {
                    b.HasBaseType("AziendaPaese.Entita.Dipendente");

                    b.HasDiscriminator().HasValue("SupervisoreReparto");
                });
#pragma warning restore 612, 618
        }
    }
}
