// <auto-generated />
using System;
using Eliminar;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eliminar.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230215093855_RElacionAttivitaExtraStudente")]
    partial class RElacionAttivitaExtraStudente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AttivitaExtracurricolariStudente", b =>
                {
                    b.Property<int>("AttivitaExtraId")
                        .HasColumnType("int");

                    b.Property<int>("StudentiId")
                        .HasColumnType("int");

                    b.HasKey("AttivitaExtraId", "StudentiId");

                    b.HasIndex("StudentiId");

                    b.ToTable("AttivitaExtracurricolariStudente");
                });

            modelBuilder.Entity("Eliminar.Entità.AttivitaExtracurricolari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AttivitaExtra");
                });

            modelBuilder.Entity("Eliminar.Entità.Corso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activate")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Inizio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Corsi");
                });

            modelBuilder.Entity("Eliminar.Entità.Matricola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("Pagamento")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Matricole");
                });

            modelBuilder.Entity("Eliminar.Entità.Professore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activate")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataNascita")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LuogoNascita")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ScuolaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScuolaId");

                    b.ToTable("Professori");
                });

            modelBuilder.Entity("Eliminar.Entità.Scuola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Citta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataFondazione")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsCattolica")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SitoWeb")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Scuola");
                });

            modelBuilder.Entity("Eliminar.Entità.Studente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataNascita")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LuogoNascita")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ScuolaId")
                        .HasColumnType("int");

                    b.Property<bool>("Studia")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ScuolaId");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("Eliminar.Entità.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataVoto")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VotoCurso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Voti");
                });

            modelBuilder.Entity("ProfessoreStudente", b =>
                {
                    b.Property<int>("ProfessoresId")
                        .HasColumnType("int");

                    b.Property<int>("StudentiId")
                        .HasColumnType("int");

                    b.HasKey("ProfessoresId", "StudentiId");

                    b.HasIndex("StudentiId");

                    b.ToTable("ProfessoreStudente");
                });

            modelBuilder.Entity("AttivitaExtracurricolariStudente", b =>
                {
                    b.HasOne("Eliminar.Entità.AttivitaExtracurricolari", null)
                        .WithMany()
                        .HasForeignKey("AttivitaExtraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eliminar.Entità.Studente", null)
                        .WithMany()
                        .HasForeignKey("StudentiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eliminar.Entità.Professore", b =>
                {
                    b.HasOne("Eliminar.Entità.Scuola", "Scuola")
                        .WithMany("Professori")
                        .HasForeignKey("ScuolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scuola");
                });

            modelBuilder.Entity("Eliminar.Entità.Studente", b =>
                {
                    b.HasOne("Eliminar.Entità.Scuola", "Scuola")
                        .WithMany()
                        .HasForeignKey("ScuolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scuola");
                });

            modelBuilder.Entity("ProfessoreStudente", b =>
                {
                    b.HasOne("Eliminar.Entità.Professore", null)
                        .WithMany()
                        .HasForeignKey("ProfessoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eliminar.Entità.Studente", null)
                        .WithMany()
                        .HasForeignKey("StudentiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eliminar.Entità.Scuola", b =>
                {
                    b.Navigation("Professori");
                });
#pragma warning restore 612, 618
        }
    }
}
