// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PianetaPersone;

#nullable disable

namespace PianetaPersone.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230223134438_RPianetaPersona")]
    partial class RPianetaPersona
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PianetaPersone.Entity.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Anni")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PianetaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PianetaId");

                    b.ToTable("Persone");
                });

            modelBuilder.Entity("PianetaPersone.Entity.Pianeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pianeti");
                });

            modelBuilder.Entity("PianetaPersone.Entity.Persona", b =>
                {
                    b.HasOne("PianetaPersone.Entity.Pianeta", "Pianeta")
                        .WithMany("Persona")
                        .HasForeignKey("PianetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pianeta");
                });

            modelBuilder.Entity("PianetaPersone.Entity.Pianeta", b =>
                {
                    b.Navigation("Persona");
                });
#pragma warning restore 612, 618
        }
    }
}
