// <auto-generated />
using System;
using EsempioDaButare;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EsempioDaButare.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230217164746_InizialConRelazioni")]
    partial class InizialConRelazioni
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DipendenteReparto", b =>
                {
                    b.Property<int>("DipendentiId")
                        .HasColumnType("int");

                    b.Property<int>("RepartiId")
                        .HasColumnType("int");

                    b.HasKey("DipendentiId", "RepartiId");

                    b.HasIndex("RepartiId");

                    b.ToTable("DipendenteReparto");
                });

            modelBuilder.Entity("EsempioDaButare.Entità.Dipendente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Anni")
                        .HasColumnType("int");

                    b.Property<int>("AnniEsperienza")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAsunzione")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("GuadagniAnnuali")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("LavoraAncora")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Dipendenti");
                });

            modelBuilder.Entity("EsempioDaButare.Entità.Diretore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Anni")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FabricaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FabricaId");

                    b.ToTable("Diretore");
                });

            modelBuilder.Entity("EsempioDaButare.Entità.Fabrica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFondazione")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Diretoreid")
                        .HasColumnType("int");

                    b.Property<decimal>("GuadagniAnnuali")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("OperativaAncora")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PaeseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Diretoreid");

                    b.HasIndex("PaeseId");

                    b.ToTable("Fabriche");
                });

            modelBuilder.Entity("EsempioDaButare.Entità.Paese", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataIndependenza")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Live")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("soldi")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Paesi");
                });

            modelBuilder.Entity("EsempioDaButare.Entità.Reparto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CapacitaDiLavoratori")
                        .HasColumnType("int");

                    b.Property<int>("FabricaId")
                        .HasColumnType("int");

                    b.Property<string>("NomeReparto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SupervisoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FabricaId");

                    b.HasIndex("SupervisoreId");

                    b.ToTable("Reparti");
                });

            modelBuilder.Entity("EsempioDaButare.Entità.Stagista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Anni")
                        .HasColumnType("int");

                    b.Property<DateTime>("FineStage")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("InizioStage")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("SoldiRicevutiInPeriodoStage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Stagisti");
                });

            modelBuilder.Entity("EsempioDaButare.Entità.Supervisore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnniEsperienza")
                        .HasColumnType("int");

                    b.Property<bool>("LavoraAncora")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Supervisori");
                });

            modelBuilder.Entity("RepartoStagista", b =>
                {
                    b.Property<int>("RepartiId")
                        .HasColumnType("int");

                    b.Property<int>("StagistiId")
                        .HasColumnType("int");

                    b.HasKey("RepartiId", "StagistiId");

                    b.HasIndex("StagistiId");

                    b.ToTable("RepartoStagista");
                });

            modelBuilder.Entity("DipendenteReparto", b =>
                {
                    b.HasOne("EsempioDaButare.Entità.Dipendente", null)
                        .WithMany()
                        .HasForeignKey("DipendentiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsempioDaButare.Entità.Reparto", null)
                        .WithMany()
                        .HasForeignKey("RepartiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EsempioDaButare.Entità.Diretore", b =>
                {
                    b.HasOne("EsempioDaButare.Entità.Fabrica", "Fabrica")
                        .WithMany()
                        .HasForeignKey("FabricaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fabrica");
                });

            modelBuilder.Entity("EsempioDaButare.Entità.Fabrica", b =>
                {
                    b.HasOne("EsempioDaButare.Entità.Diretore", "Diretore")
                        .WithMany()
                        .HasForeignKey("Diretoreid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsempioDaButare.Entità.Paese", "Paese")
                        .WithMany("Fabricas")
                        .HasForeignKey("PaeseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diretore");

                    b.Navigation("Paese");
                });

            modelBuilder.Entity("EsempioDaButare.Entità.Reparto", b =>
                {
                    b.HasOne("EsempioDaButare.Entità.Fabrica", "Fabrica")
                        .WithMany("Reparti")
                        .HasForeignKey("FabricaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsempioDaButare.Entità.Supervisore", "Supervisore")
                        .WithMany()
                        .HasForeignKey("SupervisoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fabrica");

                    b.Navigation("Supervisore");
                });

            modelBuilder.Entity("RepartoStagista", b =>
                {
                    b.HasOne("EsempioDaButare.Entità.Reparto", null)
                        .WithMany()
                        .HasForeignKey("RepartiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsempioDaButare.Entità.Stagista", null)
                        .WithMany()
                        .HasForeignKey("StagistiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EsempioDaButare.Entità.Fabrica", b =>
                {
                    b.Navigation("Reparti");
                });

            modelBuilder.Entity("EsempioDaButare.Entità.Paese", b =>
                {
                    b.Navigation("Fabricas");
                });
#pragma warning restore 612, 618
        }
    }
}
