// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Regolo2020.Ambienti.A28ControlloDiGestione.DataModels;

#nullable disable

namespace Regolo2020.Ambienti.A28ControlloDiGestione.DataModels.Migrations
{
    [DbContext(typeof(A28ControlloDiGestioneDbContext))]
    [Migration("20230221110015_CreazioneTabellaMovimenti")]
    partial class CreazioneTabellaMovimenti
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Regolo2020.Ambienti.A28ControlloDiGestione.DataModels.Tables.A280001Movimenti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Avere")
                        .HasColumnType("double");

                    b.Property<string>("Causale")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("Dare")
                        .HasColumnType("double");

                    b.Property<DateTime>("DataDocumento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataRegistrazione")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescrizioneRiga")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("IdControparte")
                        .HasColumnType("int");

                    b.Property<string>("NomeFile")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroDocumentoContropartita")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroMovimento")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("a280001_movimenti", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
