// <auto-generated />
using System;
using EsercizioNuovoEliminare;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EsercizioNuovoEliminare.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230222105616_Iniziale")]
    partial class Iniziale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.Clase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clasi");
                });

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.CorsoTotale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descrizione")
                        .HasColumnType("longtext");

                    b.Property<bool?>("InCorso")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("Inizio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Ore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Corsi_Totali");
                });

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.Docente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Citta")
                        .HasColumnType("longtext");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataDiNascita")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("InCorso")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("longtext");

                    b.Property<string>("Nazionalita")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("OreDilavoro")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Docenti");
                });

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataInizio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descrizione")
                        .HasColumnType("longtext");

                    b.Property<bool?>("InCorso")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Ore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Materie");
                });

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.Postazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Postazioni");
                });

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.Scuola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Citta")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SitoWeb")
                        .HasColumnType("longtext");

                    b.Property<string>("Storia")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Scuole");
                });

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.Studente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Anni")
                        .HasColumnType("int");

                    b.Property<string>("Citta")
                        .HasColumnType("longtext");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataDiNascita")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("longtext");

                    b.Property<string>("Nazionalita")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Studenti");
                });
#pragma warning restore 612, 618
        }
    }
}
