// <auto-generated />
using System;
using EsercizioNuovoEliminare;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EsercizioNuovoEliminare.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230222140938_Relazioni")]
    partial class Relazioni
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.Clase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ScuolaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId")
                        .IsUnique();

                    b.HasIndex("ScuolaId");

                    b.ToTable("Clasi");
                });

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.CorsoTotale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descrizione")
                        .HasColumnType("longtext");

                    b.Property<bool?>("InCorso")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("Inizio")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Ore")
                        .HasColumnType("int");

                    b.Property<int>("ScuolaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScuolaId");

                    b.ToTable("Corsi_Totali");
                });

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.Docente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Citta")
                        .HasColumnType("longtext");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataDiNascita")
                        .HasColumnType("date");

                    b.Property<bool?>("InCorso")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("longtext");

                    b.Property<string>("Nazionalita")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("OreDilavoro")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Docenti");
                });

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CorsoTotaleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataInizio")
                        .HasColumnType("date");

                    b.Property<string>("Descrizione")
                        .HasColumnType("longtext");

                    b.Property<int>("DocenteId")
                        .HasColumnType("int");

                    b.Property<bool?>("InCorso")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Ore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CorsoTotaleId");

                    b.HasIndex("DocenteId")
                        .IsUnique();

                    b.ToTable("Materie");
                });

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.Postazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClaseId")
                        .HasColumnType("int");

                    b.Property<int>("DocenteId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StudenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.HasIndex("DocenteId")
                        .IsUnique();

                    b.HasIndex("StudenteId")
                        .IsUnique();

                    b.ToTable("Postazioni");
                });

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.Scuola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Citta")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SitoWeb")
                        .HasColumnType("longtext");

                    b.Property<string>("Storia")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Scuole");
                });

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.Studente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Anni")
                        .HasColumnType("int");

                    b.Property<string>("Citta")
                        .HasColumnType("longtext");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CorsoTotaleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataDiNascita")
                        .HasColumnType("date");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("longtext");

                    b.Property<string>("Nazionalita")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CorsoTotaleId");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("MateriaStudente", b =>
                {
                    b.Property<int>("MaterieId")
                        .HasColumnType("int");

                    b.Property<int>("StudenteId")
                        .HasColumnType("int");

                    b.HasKey("MaterieId", "StudenteId");

                    b.HasIndex("StudenteId");

                    b.ToTable("MateriaStudente");
                });

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.Clase", b =>
                {
                    b.HasOne("EsercizioNuovoEliminare.Entità.Materia", "Materia")
                        .WithOne("Clase")
                        .HasForeignKey("EsercizioNuovoEliminare.Entità.Clase", "MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsercizioNuovoEliminare.Entità.Scuola", "Scuola")
                        .WithMany("Clasi")
                        .HasForeignKey("ScuolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("Scuola");
                });

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.CorsoTotale", b =>
                {
                    b.HasOne("EsercizioNuovoEliminare.Entità.Scuola", "Scuola")
                        .WithMany("Corsi_Totale")
                        .HasForeignKey("ScuolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scuola");
                });

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.Materia", b =>
                {
                    b.HasOne("EsercizioNuovoEliminare.Entità.CorsoTotale", "CorsoTotale")
                        .WithMany("Materie")
                        .HasForeignKey("CorsoTotaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsercizioNuovoEliminare.Entità.Docente", "Docente")
                        .WithOne("Materia")
                        .HasForeignKey("EsercizioNuovoEliminare.Entità.Materia", "DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CorsoTotale");

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.Postazione", b =>
                {
                    b.HasOne("EsercizioNuovoEliminare.Entità.Clase", "Clase")
                        .WithMany("Postazioni")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsercizioNuovoEliminare.Entità.Docente", "Docente")
                        .WithOne("Postazione")
                        .HasForeignKey("EsercizioNuovoEliminare.Entità.Postazione", "DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsercizioNuovoEliminare.Entità.Studente", "Studente")
                        .WithOne("Postazione")
                        .HasForeignKey("EsercizioNuovoEliminare.Entità.Postazione", "StudenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");

                    b.Navigation("Docente");

                    b.Navigation("Studente");
                });

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.Studente", b =>
                {
                    b.HasOne("EsercizioNuovoEliminare.Entità.CorsoTotale", "CorsoTotale")
                        .WithMany()
                        .HasForeignKey("CorsoTotaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CorsoTotale");
                });

            modelBuilder.Entity("MateriaStudente", b =>
                {
                    b.HasOne("EsercizioNuovoEliminare.Entità.Materia", null)
                        .WithMany()
                        .HasForeignKey("MaterieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsercizioNuovoEliminare.Entità.Studente", null)
                        .WithMany()
                        .HasForeignKey("StudenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.Clase", b =>
                {
                    b.Navigation("Postazioni");
                });

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.CorsoTotale", b =>
                {
                    b.Navigation("Materie");
                });

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.Docente", b =>
                {
                    b.Navigation("Materia")
                        .IsRequired();

                    b.Navigation("Postazione")
                        .IsRequired();
                });

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.Materia", b =>
                {
                    b.Navigation("Clase")
                        .IsRequired();
                });

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.Scuola", b =>
                {
                    b.Navigation("Clasi");

                    b.Navigation("Corsi_Totale");
                });

            modelBuilder.Entity("EsercizioNuovoEliminare.Entità.Studente", b =>
                {
                    b.Navigation("Postazione")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
